# StyLua configuration for ComputerCraft/OpenComputers
# CC/OC use 2-space indentation traditionally

column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
